---
- name: frontend_service
  systemd:
    name: "{{ frontend_service_name }}"
    daemon-reload: yes
    state: restarted
  become: yes

- name: npm_dependencies
  npm:
    path: "{{ frontend_app_path }}"
    executable: "{{ updated_npm_path }} --node-flags --max-old-space-size=512"
  become_user: "{{ frontend_user }}"
  become: yes
  notify: frontend_service
